// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ImageMosaic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ImageMosaic.proto</summary>
public static partial class ImageMosaicReflection {

  #region Descriptor
  /// <summary>File descriptor for ImageMosaic.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ImageMosaicReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFJbWFnZU1vc2FpYy5wcm90bxoUSW1hZ2VGaWxlSW5kZXgucHJvdG8aE0Vk",
          "Z2VEZXRlY3Rpb24ucHJvdG8ijAIKEkltYWdlTW9zYWljUmVxdWVzdBIKCgJJ",
          "ZBgBIAEoCRInCgVUaWxlcxgCIAMoCzIYLkltYWdlRmlsZUluZGV4U3RydWN0",
          "dXJlEigKBk1hc3RlchgDIAEoCzIYLkltYWdlRmlsZUluZGV4U3RydWN0dXJl",
          "Eg4KBlJhbmRvbRgEIAEoCBIRCgl0aWxlV2lkdGgYBSABKAUSEgoKdGlsZUhl",
          "aWdodBgGIAEoBRIVCg1Db2xvdXJCbGVuZGVkGAcgASgIEhAKCEVuaGFuY2Vk",
          "GAggASgIEhUKDUVkZ2VEZXRlY3Rpb24YCSABKAgSIAoFZWRnZXMYCiADKAsy",
          "ES5QaXhlbENvb3JkaW5hdGVzIjYKE0ltYWdlTW9zYWljUmVzcG9uc2USEAoI",
          "bG9jYXRpb24YASABKAkSDQoFRXJyb3IYAiABKAkiRAoYTWFzdGVySW1hZ2VD",
          "b2xvdXJSZXF1ZXN0EigKBk1hc3RlchgBIAEoCzIYLkltYWdlRmlsZUluZGV4",
          "U3RydWN0dXJlIjQKGU1hc3RlckltYWdlQ29sb3VyUmVzcG9uc2USFwoPQXZl",
          "cmFnZVRpbGVBUkdCGAEgAygFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ImageFileIndexReflection.Descriptor, global::EdgeDetectionReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ImageMosaicRequest), global::ImageMosaicRequest.Parser, new[]{ "Id", "Tiles", "Master", "Random", "TileWidth", "TileHeight", "ColourBlended", "Enhanced", "EdgeDetection", "Edges" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ImageMosaicResponse), global::ImageMosaicResponse.Parser, new[]{ "Location", "Error" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MasterImageColourRequest), global::MasterImageColourRequest.Parser, new[]{ "Master" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MasterImageColourResponse), global::MasterImageColourResponse.Parser, new[]{ "AverageTileARGB" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ImageMosaicRequest : pb::IMessage<ImageMosaicRequest> {
  private static readonly pb::MessageParser<ImageMosaicRequest> _parser = new pb::MessageParser<ImageMosaicRequest>(() => new ImageMosaicRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ImageMosaicRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ImageMosaicReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicRequest(ImageMosaicRequest other) : this() {
    id_ = other.id_;
    tiles_ = other.tiles_.Clone();
    master_ = other.master_ != null ? other.master_.Clone() : null;
    random_ = other.random_;
    tileWidth_ = other.tileWidth_;
    tileHeight_ = other.tileHeight_;
    colourBlended_ = other.colourBlended_;
    enhanced_ = other.enhanced_;
    edgeDetection_ = other.edgeDetection_;
    edges_ = other.edges_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicRequest Clone() {
    return new ImageMosaicRequest(this);
  }

  /// <summary>Field number for the "Id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Tiles" field.</summary>
  public const int TilesFieldNumber = 2;
  private static readonly pb::FieldCodec<global::ImageFileIndexStructure> _repeated_tiles_codec
      = pb::FieldCodec.ForMessage(18, global::ImageFileIndexStructure.Parser);
  private readonly pbc::RepeatedField<global::ImageFileIndexStructure> tiles_ = new pbc::RepeatedField<global::ImageFileIndexStructure>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::ImageFileIndexStructure> Tiles {
    get { return tiles_; }
  }

  /// <summary>Field number for the "Master" field.</summary>
  public const int MasterFieldNumber = 3;
  private global::ImageFileIndexStructure master_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ImageFileIndexStructure Master {
    get { return master_; }
    set {
      master_ = value;
    }
  }

  /// <summary>Field number for the "Random" field.</summary>
  public const int RandomFieldNumber = 4;
  private bool random_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Random {
    get { return random_; }
    set {
      random_ = value;
    }
  }

  /// <summary>Field number for the "tileWidth" field.</summary>
  public const int TileWidthFieldNumber = 5;
  private int tileWidth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int TileWidth {
    get { return tileWidth_; }
    set {
      tileWidth_ = value;
    }
  }

  /// <summary>Field number for the "tileHeight" field.</summary>
  public const int TileHeightFieldNumber = 6;
  private int tileHeight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int TileHeight {
    get { return tileHeight_; }
    set {
      tileHeight_ = value;
    }
  }

  /// <summary>Field number for the "ColourBlended" field.</summary>
  public const int ColourBlendedFieldNumber = 7;
  private bool colourBlended_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool ColourBlended {
    get { return colourBlended_; }
    set {
      colourBlended_ = value;
    }
  }

  /// <summary>Field number for the "Enhanced" field.</summary>
  public const int EnhancedFieldNumber = 8;
  private bool enhanced_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Enhanced {
    get { return enhanced_; }
    set {
      enhanced_ = value;
    }
  }

  /// <summary>Field number for the "EdgeDetection" field.</summary>
  public const int EdgeDetectionFieldNumber = 9;
  private bool edgeDetection_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool EdgeDetection {
    get { return edgeDetection_; }
    set {
      edgeDetection_ = value;
    }
  }

  /// <summary>Field number for the "edges" field.</summary>
  public const int EdgesFieldNumber = 10;
  private static readonly pb::FieldCodec<global::PixelCoordinates> _repeated_edges_codec
      = pb::FieldCodec.ForMessage(82, global::PixelCoordinates.Parser);
  private readonly pbc::RepeatedField<global::PixelCoordinates> edges_ = new pbc::RepeatedField<global::PixelCoordinates>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::PixelCoordinates> Edges {
    get { return edges_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ImageMosaicRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ImageMosaicRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if(!tiles_.Equals(other.tiles_)) return false;
    if (!object.Equals(Master, other.Master)) return false;
    if (Random != other.Random) return false;
    if (TileWidth != other.TileWidth) return false;
    if (TileHeight != other.TileHeight) return false;
    if (ColourBlended != other.ColourBlended) return false;
    if (Enhanced != other.Enhanced) return false;
    if (EdgeDetection != other.EdgeDetection) return false;
    if(!edges_.Equals(other.edges_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    hash ^= tiles_.GetHashCode();
    if (master_ != null) hash ^= Master.GetHashCode();
    if (Random != false) hash ^= Random.GetHashCode();
    if (TileWidth != 0) hash ^= TileWidth.GetHashCode();
    if (TileHeight != 0) hash ^= TileHeight.GetHashCode();
    if (ColourBlended != false) hash ^= ColourBlended.GetHashCode();
    if (Enhanced != false) hash ^= Enhanced.GetHashCode();
    if (EdgeDetection != false) hash ^= EdgeDetection.GetHashCode();
    hash ^= edges_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    tiles_.WriteTo(output, _repeated_tiles_codec);
    if (master_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Master);
    }
    if (Random != false) {
      output.WriteRawTag(32);
      output.WriteBool(Random);
    }
    if (TileWidth != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(TileWidth);
    }
    if (TileHeight != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TileHeight);
    }
    if (ColourBlended != false) {
      output.WriteRawTag(56);
      output.WriteBool(ColourBlended);
    }
    if (Enhanced != false) {
      output.WriteRawTag(64);
      output.WriteBool(Enhanced);
    }
    if (EdgeDetection != false) {
      output.WriteRawTag(72);
      output.WriteBool(EdgeDetection);
    }
    edges_.WriteTo(output, _repeated_edges_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    size += tiles_.CalculateSize(_repeated_tiles_codec);
    if (master_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Master);
    }
    if (Random != false) {
      size += 1 + 1;
    }
    if (TileWidth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TileWidth);
    }
    if (TileHeight != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TileHeight);
    }
    if (ColourBlended != false) {
      size += 1 + 1;
    }
    if (Enhanced != false) {
      size += 1 + 1;
    }
    if (EdgeDetection != false) {
      size += 1 + 1;
    }
    size += edges_.CalculateSize(_repeated_edges_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ImageMosaicRequest other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    tiles_.Add(other.tiles_);
    if (other.master_ != null) {
      if (master_ == null) {
        master_ = new global::ImageFileIndexStructure();
      }
      Master.MergeFrom(other.Master);
    }
    if (other.Random != false) {
      Random = other.Random;
    }
    if (other.TileWidth != 0) {
      TileWidth = other.TileWidth;
    }
    if (other.TileHeight != 0) {
      TileHeight = other.TileHeight;
    }
    if (other.ColourBlended != false) {
      ColourBlended = other.ColourBlended;
    }
    if (other.Enhanced != false) {
      Enhanced = other.Enhanced;
    }
    if (other.EdgeDetection != false) {
      EdgeDetection = other.EdgeDetection;
    }
    edges_.Add(other.edges_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          tiles_.AddEntriesFrom(input, _repeated_tiles_codec);
          break;
        }
        case 26: {
          if (master_ == null) {
            master_ = new global::ImageFileIndexStructure();
          }
          input.ReadMessage(master_);
          break;
        }
        case 32: {
          Random = input.ReadBool();
          break;
        }
        case 40: {
          TileWidth = input.ReadInt32();
          break;
        }
        case 48: {
          TileHeight = input.ReadInt32();
          break;
        }
        case 56: {
          ColourBlended = input.ReadBool();
          break;
        }
        case 64: {
          Enhanced = input.ReadBool();
          break;
        }
        case 72: {
          EdgeDetection = input.ReadBool();
          break;
        }
        case 82: {
          edges_.AddEntriesFrom(input, _repeated_edges_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class ImageMosaicResponse : pb::IMessage<ImageMosaicResponse> {
  private static readonly pb::MessageParser<ImageMosaicResponse> _parser = new pb::MessageParser<ImageMosaicResponse>(() => new ImageMosaicResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ImageMosaicResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ImageMosaicReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicResponse(ImageMosaicResponse other) : this() {
    location_ = other.location_;
    error_ = other.error_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ImageMosaicResponse Clone() {
    return new ImageMosaicResponse(this);
  }

  /// <summary>Field number for the "location" field.</summary>
  public const int LocationFieldNumber = 1;
  private string location_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Location {
    get { return location_; }
    set {
      location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ImageMosaicResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ImageMosaicResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Location != other.Location) return false;
    if (Error != other.Error) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Location.Length != 0) hash ^= Location.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Location.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Location);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Location.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ImageMosaicResponse other) {
    if (other == null) {
      return;
    }
    if (other.Location.Length != 0) {
      Location = other.Location;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Location = input.ReadString();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class MasterImageColourRequest : pb::IMessage<MasterImageColourRequest> {
  private static readonly pb::MessageParser<MasterImageColourRequest> _parser = new pb::MessageParser<MasterImageColourRequest>(() => new MasterImageColourRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MasterImageColourRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ImageMosaicReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourRequest(MasterImageColourRequest other) : this() {
    master_ = other.master_ != null ? other.master_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourRequest Clone() {
    return new MasterImageColourRequest(this);
  }

  /// <summary>Field number for the "Master" field.</summary>
  public const int MasterFieldNumber = 1;
  private global::ImageFileIndexStructure master_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ImageFileIndexStructure Master {
    get { return master_; }
    set {
      master_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MasterImageColourRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MasterImageColourRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Master, other.Master)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (master_ != null) hash ^= Master.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (master_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Master);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (master_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Master);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MasterImageColourRequest other) {
    if (other == null) {
      return;
    }
    if (other.master_ != null) {
      if (master_ == null) {
        master_ = new global::ImageFileIndexStructure();
      }
      Master.MergeFrom(other.Master);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (master_ == null) {
            master_ = new global::ImageFileIndexStructure();
          }
          input.ReadMessage(master_);
          break;
        }
      }
    }
  }

}

public sealed partial class MasterImageColourResponse : pb::IMessage<MasterImageColourResponse> {
  private static readonly pb::MessageParser<MasterImageColourResponse> _parser = new pb::MessageParser<MasterImageColourResponse>(() => new MasterImageColourResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MasterImageColourResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ImageMosaicReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourResponse(MasterImageColourResponse other) : this() {
    averageTileARGB_ = other.averageTileARGB_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MasterImageColourResponse Clone() {
    return new MasterImageColourResponse(this);
  }

  /// <summary>Field number for the "AverageTileARGB" field.</summary>
  public const int AverageTileARGBFieldNumber = 1;
  private static readonly pb::FieldCodec<int> _repeated_averageTileARGB_codec
      = pb::FieldCodec.ForInt32(10);
  private readonly pbc::RepeatedField<int> averageTileARGB_ = new pbc::RepeatedField<int>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<int> AverageTileARGB {
    get { return averageTileARGB_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MasterImageColourResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MasterImageColourResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!averageTileARGB_.Equals(other.averageTileARGB_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= averageTileARGB_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    averageTileARGB_.WriteTo(output, _repeated_averageTileARGB_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += averageTileARGB_.CalculateSize(_repeated_averageTileARGB_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MasterImageColourResponse other) {
    if (other == null) {
      return;
    }
    averageTileARGB_.Add(other.averageTileARGB_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          averageTileARGB_.AddEntriesFrom(input, _repeated_averageTileARGB_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
